### PR TITLE
[fix]: [CDS-85006]: Add region field to aws connector

### PR DESCRIPTION
**Pull request by PragyeshMishra01**
## Describe your changes
Added support for aws region field in aws connector.
## Comment Triggers

<details>
  <summary>PR Check triggers</summary>
  
- Build: `trigger build`
- gitleaks: `trigger gitleaks`

### CODE REVIEW

**Review by piyush-bhuwalka — APPROVED** [review]

**Comment by PragyeshMishra01** [comment]
trigger gitleaks

**Comment by PragyeshMishra01** [comment]
trigger gitleaks

**Comment by PragyeshMishra01** [comment]
trigger gitleaks

**Comment by PragyeshMishra01** [comment]
trigger gitleaks

**Comment by adiyaar24** [comment]
trigger gitleaks

**Comment by anshul-harness** [comment]
trigger gitleaks

**Review by shalinlk — COMMENTED** [review]
No change in example files ?

**Comment by krishi0408** [comment]
trigger gitleaks

**Pull request merged**
