### PR TITLE
feat: Add oidc authentication as valid auth type

### PR DESCRIPTION
**Pull request by eahrend**
## Describe your changes
Adds oidc authentication as a valid GCP connector authentication type.
## Comment Triggers

<details>
  <summary>PR Check triggers</summary>
  
- Build: `trigger build`
- gitleaks: `trigger gitleaks`

### CODE REVIEW

**Comment by eahrend** [comment]
@Raghav-Murali it looks like the checks are failing, but I don't have permission to run them or check what the status of them are. Is this expected?

**Comment by Raghav-Murali** [comment]
trigger build, gitleaks

**Comment by eahrend** [comment]
trigger gitleaks

**Comment by eahrend** [comment]
@Raghav-Murali Looks like it is building fine, but I can't see why gitleaks is failing

**Review by gn-harness — APPROVED** [review]

**Comment by Vbhatia20** [comment]
trigger gitleaks

**Pull request merged**
